### PR TITLE
Add secops guides for network and hosts

### PR DESCRIPTION
**Pull request by karenzone**
Continuation from #189 

https://preview-docs.firebaseapp.com/network/
https://preview-docs.firebaseapp.com/hosts/

### CODE REVIEW

**Comment by nik9000** [comment]
The PR tests here found *something* but they didn't log things very well......

**Comment by karenzone** [comment]
@elastic/secops I've updated the docs framework to give you two books (network and hosts) based on comments from  @andrewkroh in #189.  Picturing a new book based on asciidoc files can be tough, so I've put up rendered versions here: 
https://preview-docs.firebaseapp.com/network/
https://preview-docs.firebaseapp.com/hosts/

DeDe wrote our first solution guide for Infrastructure (https://www.elastic.co/guide/en/infrastructure/guide/current/index.html).  Her guide has a nice user-centered flow to it, and I've followed her info architecture in these new security guides. 

We'll also need to add some info similar to [this](https://www.elastic.co/guide/en/kibana/current/xpack-infra.html) to the Kibana Reference.

**Comment by tsg** [comment]
@karenzone I've noticed a `.DS_store` file in the PR, you should remove that.

**Comment by nik9000** [comment]
Since this test is a new one from me I'll see what I can find locally.

**Comment by nik9000** [comment]
OK! The tests are failing because your PR is quite out of date with master and it is missing some files that it needs to run the tests, specifically it is missing the "installation and upgrade guide". Merging mater into this branch ought to fix it. I'll improve the error message in the mean time.

**Pull request merged**
