### PR TITLE
a small correction ins the upgrade process.

### PR DESCRIPTION
**Pull request by nimarezainia**
Addressing https://github.com/elastic/sdh-beats/issues/3175

### CODE REVIEW

**Comment by nimarezainia** [comment]
Hi @karenzone , should I be merging this?

**Review by karenzone — APPROVED** [review]
Using version attributes is always preferable to hard coding. Thank you for making this fix. 
I also suggested some product name attributes for your consideration. 

Otherwise, LGTM

**Comment by karenzone** [comment]
Here's a preview if you'd like to check it out: https://stack-docs_2350.docs-preview.app.elstc.co/guide/en/elastic-stack/master/upgrading-elastic-stack.html#prepare-to-upgrade

**Comment by Leaf-Lin** [comment]
Can someone fix this please?

**Comment by karenzone** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by karenzone — APPROVED** [review]

**Comment by karenzone** [comment]
49784

**Pull request merged**
