### PR TITLE
Gke on prem integration stack docs issue 255

### PR DESCRIPTION
**Pull request by DanRoscigno**
These docs support the integration between GKE On-Prem and the Elastic Stack.

### CODE REVIEW

**Comment by DanRoscigno** [comment]
@lcawl I submitted the PR.

**Comment by asawariS** [comment]
Thanks @DanRoscigno I don't need to be a reviewer on this. I assume this has gone through a tech review, perhaps with someone from Ingest team?

**Comment by DanRoscigno** [comment]
Yes @asawariS , it has been reviewed by engineering and Jamie.

**Comment by asawariS** [comment]
thanks @DanRoscigno. If @lcawl is good with it, let's ship it.

**Pull request merged**
