### PR TITLE
Updates the Kibana breaking changes link

### PR DESCRIPTION
**Pull request by KOTungseth**

### CODE REVIEW

**Comment by lcawl** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by KOTungseth** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by KOTungseth** [comment]
skiplinkcheck

**Comment by KOTungseth** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by KOTungseth** [comment]
@elasticmachine merge upstream

**Comment by KOTungseth** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by KOTungseth** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
