### PR TITLE
[DOCS] Update APM transaction module description

### PR DESCRIPTION
**Pull request by lcawl**
Relates to https://github.com/elastic/kibana/issues/101734

This PR updates the details in [APM anomaly detection configurations](https://www.elastic.co/guide/en/machine-learning/master/ootb-ml-jobs-apm.html) to reflect the changes in 
https://github.com/elastic/kibana/tree/main/x-pack/plugins/ml/server/models/data_recognizer/modules/apm_transaction

### Preview

https://stack-docs_1954.docs-preview.app.elstc.co/guide/en/machine-learning/master/ootb-ml-jobs-apm.html

### CODE REVIEW

**Review by szabosteve — APPROVED** [review]
I think it's a great solution! LGTM.

**Comment by panbalag** [comment]
The manifest file mentions "failure rate" while the description in the doc mentions "error percentage" - should this be consistent?

**Comment by szabosteve** [comment]
Hey @panbalag, 

Nice to see you here! 👋 😄 
While the manifest file does mention "failure rate", the module description itself uses the term "error percentage". You can find the module description here: https://github.com/elastic/kibana/blob/3d8697d967f0b2ddcd1ab3b3693134d825fc5f2b/x-pack/plugins/ml/server/models/data_recognizer/modules/apm_transaction/ml/apm_tx_metrics.json#L6
I think the doc is consistent with the module description, however, you might be right and it should be considered to streamline the manifest file terminology to be in line with the module descriptions.

**Comment by panbalag** [comment]
Sounds good :+1:  In that case I will cast my vote for LGTM

**Review by peteharverson — APPROVED** [review]
LGTM

**Pull request merged**
